var goog;
var WebSocketClient;
WebSocketClient.prototype.abort;
var encodeURIComponent;
var decodeURIComponent;
Window.prototype.setTimeout;
Object.exec;
Object.index;
Object.install;
WebSocket.prototype.onerror;
Int8Array.prototype.set;
Int8Array.prototype.fill;
Int8Array.prototype.length;
var WebSocketConnection;
WebSocketConnection.prototype.close;
WebSocketConnection.prototype.sendBytes;
WebSocketConnection.prototype.on;
Function.prototype.hrtime;
var Buffer;
var JSEnv;
goog.global;
goog.isArrayLike;
var process;
process.argv;
process.hrtime;
var require;
Uint8Array.prototype.length;
var setTimeout;
var module;
module.exports;
RegExp.prototype.schema$core$Schema$;
RegExp.prototype.schema$core$Schema$spec$arity$1;
RegExp.prototype.schema$core$Schema$explain$arity$1;
