/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mydomain;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class LoginRsp extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3892311088099720226L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LoginRsp\",\"namespace\":\"mydomain\",\"fields\":[{\"name\":\"was_successful\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LoginRsp> ENCODER =
      new BinaryMessageEncoder<LoginRsp>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LoginRsp> DECODER =
      new BinaryMessageDecoder<LoginRsp>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<LoginRsp> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<LoginRsp> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LoginRsp>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this LoginRsp to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a LoginRsp from a ByteBuffer. */
  public static LoginRsp fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public boolean was_successful;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LoginRsp() {}

  /**
   * All-args constructor.
   * @param was_successful The new value for was_successful
   */
  public LoginRsp(java.lang.Boolean was_successful) {
    this.was_successful = was_successful;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return was_successful;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: was_successful = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'was_successful' field.
   * @return The value of the 'was_successful' field.
   */
  public java.lang.Boolean getWasSuccessful() {
    return was_successful;
  }

  /**
   * Sets the value of the 'was_successful' field.
   * @param value the value to set.
   */
  public void setWasSuccessful(java.lang.Boolean value) {
    this.was_successful = value;
  }

  /**
   * Creates a new LoginRsp RecordBuilder.
   * @return A new LoginRsp RecordBuilder
   */
  public static mydomain.LoginRsp.Builder newBuilder() {
    return new mydomain.LoginRsp.Builder();
  }

  /**
   * Creates a new LoginRsp RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LoginRsp RecordBuilder
   */
  public static mydomain.LoginRsp.Builder newBuilder(mydomain.LoginRsp.Builder other) {
    return new mydomain.LoginRsp.Builder(other);
  }

  /**
   * Creates a new LoginRsp RecordBuilder by copying an existing LoginRsp instance.
   * @param other The existing instance to copy.
   * @return A new LoginRsp RecordBuilder
   */
  public static mydomain.LoginRsp.Builder newBuilder(mydomain.LoginRsp other) {
    return new mydomain.LoginRsp.Builder(other);
  }

  /**
   * RecordBuilder for LoginRsp instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LoginRsp>
    implements org.apache.avro.data.RecordBuilder<LoginRsp> {

    private boolean was_successful;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mydomain.LoginRsp.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.was_successful)) {
        this.was_successful = data().deepCopy(fields()[0].schema(), other.was_successful);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing LoginRsp instance
     * @param other The existing instance to copy.
     */
    private Builder(mydomain.LoginRsp other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.was_successful)) {
        this.was_successful = data().deepCopy(fields()[0].schema(), other.was_successful);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'was_successful' field.
      * @return The value.
      */
    public java.lang.Boolean getWasSuccessful() {
      return was_successful;
    }

    /**
      * Sets the value of the 'was_successful' field.
      * @param value The value of 'was_successful'.
      * @return This builder.
      */
    public mydomain.LoginRsp.Builder setWasSuccessful(boolean value) {
      validate(fields()[0], value);
      this.was_successful = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'was_successful' field has been set.
      * @return True if the 'was_successful' field has been set, false otherwise.
      */
    public boolean hasWasSuccessful() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'was_successful' field.
      * @return This builder.
      */
    public mydomain.LoginRsp.Builder clearWasSuccessful() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LoginRsp build() {
      try {
        LoginRsp record = new LoginRsp();
        record.was_successful = fieldSetFlags()[0] ? this.was_successful : (java.lang.Boolean) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LoginRsp>
    WRITER$ = (org.apache.avro.io.DatumWriter<LoginRsp>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LoginRsp>
    READER$ = (org.apache.avro.io.DatumReader<LoginRsp>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
